# Generated by Django 4.1.7 on 2023-02-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tehno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
